'use strict';
const API_BASE='https://suduko.mdmsportal.uk';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const E={login:$('#adminLoginView'),app:$('#adminAppView'),form:$('#adminLoginForm'),user:$('#adminUsername'),pass:$('#adminPassword'),loginMsg:$('#adminLoginMessage'),badge:$('#adminConnectionBadge'),identity:$('#adminIdentity'),logout:$('#logoutBtn'),select:$('#competitionSelect'),refresh:$('#refreshBtn'),
 noNotice:$('#noCompetitionNotice'),overview:$('#overviewContent'),eventStatus:$('#eventStatus'),eventName:$('#eventName'),eventMeta:$('#eventMeta'),toggleEvent:$('#toggleEventBtn'),leaderVisibility:$('#leaderboardVisibilityBtn'),copyCode:$('#copyCodeBtn'),stats:{registered:$('#statRegistered'),playing:$('#statPlaying'),submitted:$('#statSubmitted'),perfect:$('#statPerfect'),not_started:$('#statNotStarted')},overviewMonitor:$('#overviewMonitor'),overviewLeaderboard:$('#overviewLeaderboard'),fullMonitor:$('#fullMonitor'),fullLeaderboard:$('#fullLeaderboard'),monitorTitle:$('#monitorTitle'),
 createForm:$('#createCompetitionForm'),newName:$('#newName'),newCode:$('#newCode'),newOrg:$('#newOrg'),newDescription:$('#newDescription'),newSelfReg:$('#newSelfReg'),newShow:$('#newShowLeaderboard'),puzzleText:$('#puzzleText'),masterText:$('#masterText'),puzzleFile:$('#puzzleFile'),masterFile:$('#masterFile'),puzzlePreview:$('#puzzlePreview'),masterPreview:$('#masterPreview'),createMsg:$('#createMessage'),
 addForm:$('#addContestantForm'),addNo:$('#addNo'),addName:$('#addName'),addSchool:$('#addSchool'),contestantMsg:$('#contestantMessage'),bulk:$('#bulkContestants'),bulkBtn:$('#bulkImportBtn'),bulkMsg:$('#bulkMessage'),contestantTable:$('#contestantTable'),exportBtn:$('#exportCsvBtn'),mobileTab:$('#mobileTabSelect'),toasts:$('#adminToastStack')};
const S={token:localStorage.getItem('sudoku_live_admin_token')||'',admin:null,competitions:[],selectedId:Number(localStorage.getItem('sudoku_live_competition_id')||0),snapshot:null,socket:null,serverOffset:0};
function msg(el,text,type=''){el.textContent=text||'';el.className='form-message'+(type?` ${type}`:'');}
function toast(text,type=''){const d=document.createElement('div');d.className='toast '+type;d.textContent=text;E.toasts.appendChild(d);setTimeout(()=>d.remove(),3500)}
function setConn(mode,text){E.badge.className=`status-pill status-${mode}`;E.badge.querySelector('span:last-child').textContent=text}
function esc(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));}
function fmt(ms){ms=Math.max(0,Number(ms)||0);const m=Math.floor(ms/60000),s=Math.floor(ms%60000/1000),x=Math.floor(ms%1000);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(x).padStart(3,'0')}`}
function elapsedFrom(start,submitted,elapsed){if(elapsed!=null)return fmt(elapsed);return start?fmt((submitted||Date.now()+S.serverOffset)-start):'—'}
async function api(path,opts={}){const h={...(opts.headers||{})};if(S.token)h.Authorization=`Bearer ${S.token}`;if(opts.body&&!(opts.body instanceof FormData)){h['Content-Type']='application/json';if(typeof opts.body!=='string')opts.body=JSON.stringify(opts.body)}const r=await fetch(API_BASE+path,{...opts,headers:h});let d={};try{d=await r.json()}catch{}if(r.status===401){logoutLocal();throw new Error('Admin session expired. Please sign in again.')}if(!r.ok)throw new Error(d.error||`Request failed (${r.status})`);return d}
async function loadSocketClient(){if(window.io)return true;return new Promise(resolve=>{const s=document.createElement('script');s.src=API_BASE+'/socket.io/socket.io.js';s.onload=()=>resolve(true);s.onerror=()=>resolve(false);document.head.appendChild(s)})}
async function connectSocket(){if(!S.token)return;const ok=await loadSocketClient();if(!ok){setConn('offline','Live Sync Offline');return}if(S.socket)S.socket.disconnect();S.socket=io(API_BASE,{auth:{admin_token:S.token},reconnection:true,reconnectionDelay:700,reconnectionDelayMax:3500,transports:['polling','websocket']});S.socket.on('connect',()=>{setConn('online','Socket.IO Live');watchSelected()});S.socket.on('disconnect',()=>setConn('connecting','Reconnecting'));S.socket.on('connect_error',()=>setConn('offline','Live Sync Offline'));S.socket.on('server:hello',p=>{if(p?.server_now)S.serverOffset=p.server_now-Date.now()});S.socket.on('competition:snapshot',p=>{if(Number(p?.competition?.id)!==S.selectedId)return;S.serverOffset=(p.server_now||Date.now())-Date.now();S.snapshot=p;renderSnapshot()});S.socket.on('attempt:saved',p=>{if(S.snapshot){const r=S.snapshot.monitor?.find(x=>x.attempt_id===p.attempt_id);if(r){r.last_saved_at=p.last_saved_at;renderMonitors()}}})}
function watchSelected(){if(S.socket?.connected&&S.selectedId)S.socket.emit('admin:watch',{competition_id:S.selectedId})}
function showAdmin(){E.login.classList.remove('active');E.app.classList.add('active')}
function showLogin(){E.app.classList.remove('active');E.login.classList.add('active')}
function logoutLocal(){S.token='';localStorage.removeItem('sudoku_live_admin_token');if(S.socket)S.socket.disconnect();showLogin()}
E.form.addEventListener('submit',async e=>{e.preventDefault();msg(E.loginMsg,'Signing in…');try{const d=await api('/api/admin/login',{method:'POST',body:{username:E.user.value,password:E.pass.value}});S.token=d.token;S.admin=d.admin;localStorage.setItem('sudoku_live_admin_token',S.token);E.identity.textContent=d.admin.display_name||d.admin.username;msg(E.loginMsg,'');showAdmin();await loadCompetitions();await connectSocket()}catch(err){msg(E.loginMsg,err.message,'error')}})
E.logout.addEventListener('click',async()=>{try{await api('/api/admin/logout',{method:'POST'})}catch{}logoutLocal()});
async function loadCompetitions(){const d=await api('/api/admin/competitions');S.competitions=d.competitions||[];E.select.innerHTML='';if(!S.competitions.length){const o=document.createElement('option');o.textContent='No competitions';o.value='';E.select.appendChild(o);S.selectedId=0;renderNoCompetition();return}if(!S.selectedId||!S.competitions.some(c=>c.id===S.selectedId))S.selectedId=S.competitions[0].id;for(const c of S.competitions){const o=document.createElement('option');o.value=c.id;o.textContent=`${c.code} — ${c.name}`;o.selected=c.id===S.selectedId;E.select.appendChild(o)}localStorage.setItem('sudoku_live_competition_id',S.selectedId);await fetchSnapshot()}
E.select.addEventListener('change',async()=>{S.selectedId=Number(E.select.value);localStorage.setItem('sudoku_live_competition_id',S.selectedId);await fetchSnapshot();watchSelected()});
E.refresh.addEventListener('click',()=>fetchSnapshot(true));
async function fetchSnapshot(showToast=false){if(!S.selectedId)return renderNoCompetition();try{const d=await api(`/api/admin/competitions/${S.selectedId}/snapshot`);S.snapshot=d;renderSnapshot();if(showToast)toast('Live state resynced.','success')}catch(err){toast(err.message,'error')}}
function renderNoCompetition(){E.noNotice.classList.remove('hidden');E.overview.classList.add('hidden');S.snapshot=null;renderMonitors();renderRankings();renderContestants()}
function renderSnapshot(){const x=S.snapshot;if(!x)return renderNoCompetition();E.noNotice.classList.add('hidden');E.overview.classList.remove('hidden');const c=x.competition;E.eventStatus.textContent=c.status.toUpperCase();E.eventStatus.style.color=c.status==='open'?'var(--green)':c.status==='closed'?'var(--red)':'var(--gold)';E.eventName.textContent=c.name;E.eventMeta.textContent=`${c.code}${c.organization?' · '+c.organization:''}`;E.toggleEvent.textContent=c.status==='open'?'Close Competition':(c.status==='closed'?'Reopen Competition':'Open Competition');E.toggleEvent.className='btn '+(c.status==='open'?'btn-danger':'btn-success');E.leaderVisibility.textContent=`Leaderboard: ${c.show_live_leaderboard?'Visible':'Hidden'}`;for(const [k,el] of Object.entries(E.stats))el.textContent=x.stats?.[k]??0;E.monitorTitle.textContent=c.name;renderMonitors();renderLeaderboards();renderContestants()}
E.toggleEvent.addEventListener('click',async()=>{if(!S.snapshot)return;const c=S.snapshot.competition;const action=c.status==='open'?'close':'open';try{await api(`/api/admin/competitions/${c.id}/${action}`,{method:'POST'});toast(action==='open'?'Competition opened.':'Competition closed.','success');await fetchSnapshot()}catch(err){toast(err.message,'error')}})
E.leaderVisibility.addEventListener('click',async()=>{if(!S.snapshot)return;try{await api(`/api/admin/competitions/${S.selectedId}`,{method:'PATCH',body:{show_live_leaderboard:!S.snapshot.competition.show_live_leaderboard}});toast('Leaderboard visibility updated.','success');await fetchSnapshot()}catch(err){toast(err.message,'error')}})
E.copyCode.addEventListener('click',async()=>{if(!S.snapshot)return;try{await navigator.clipboard.writeText(S.snapshot.competition.code);toast('Competition code copied.','success')}catch{toast(S.snapshot.competition.code)}})
function renderMonitors(){const rows=S.snapshot?.monitor||[];const html=!rows.length?'<p class="muted small">No contestants yet.</p>':`<table class="data-table"><thead><tr><th>CONTESTANT</th><th>STATUS</th><th>ELAPSED</th><th>LAST SYNC</th><th>RESULT</th></tr></thead><tbody>${rows.map(r=>{const st=!r.attempt_id?'waiting':r.state;return `<tr><td class="table-name"><strong>${esc(r.full_name)}</strong><small>${esc(r.contestant_no)}${r.school_team?' · '+esc(r.school_team):''}</small></td><td><span class="state-chip ${st}">${st.toUpperCase()}</span></td><td class="live-elapsed" data-start="${r.started_at||''}" data-submitted="${r.submitted_at||''}" data-elapsed="${r.elapsed_ms??''}">${elapsedFrom(r.started_at,r.submitted_at,r.elapsed_ms)}</td><td>${r.last_saved_at?new Date(r.last_saved_at).toLocaleTimeString():'—'}</td><td>${r.state==='submitted'?(r.is_perfect?'<span class="state-chip submitted">PERFECT</span>':`<span class="state-chip incorrect">${r.correct_count||0}/81</span>`):'—'}</td></tr>`}).join('')}</tbody></table>`;E.overviewMonitor.innerHTML=html;E.fullMonitor.innerHTML=html}
function renderLeaderboards(){const rows=S.snapshot?.leaderboard||[];E.overviewLeaderboard.innerHTML=!rows.length?'<p class="muted small">No submissions yet.</p>':rows.slice(0,8).map(r=>`<div class="leader-row"><span class="rank-no ${r.rank<=3?'podium':''}">#${r.rank}</span><span class="leader-name"><strong>${esc(r.full_name)}</strong><small>${esc(r.contestant_no)} · ${r.correct_count}/81</small></span><span class="leader-time"><strong>${fmt(r.elapsed_ms)}</strong><small>${Number(r.accuracy).toFixed(1)}%</small></span></div>`).join('');renderRankings()}
function renderRankings(){const rows=S.snapshot?.leaderboard||[];E.fullLeaderboard.innerHTML=`<div class="ranking-row header"><span>RANK</span><span>CONTESTANT</span><span>SCHOOL / TEAM</span><span>CORRECT</span><span>ACCURACY</span><span>TIME</span></div>`+(!rows.length?'<p class="muted small">No submitted results yet.</p>':rows.map(r=>`<div class="ranking-row ${r.rank<=3?'top':''}"><span class="rnk">#${r.rank}</span><span class="who"><strong>${esc(r.full_name)}</strong><small>${esc(r.contestant_no)}</small></span><span>${esc(r.school_team||'—')}</span><span>${r.correct_count}/81</span><span>${Number(r.accuracy).toFixed(2)}%</span><span>${fmt(r.elapsed_ms)}</span></div>`).join(''))}
function renderContestants(){const rows=S.snapshot?.monitor||[];E.contestantTable.innerHTML=!rows.length?'<p class="muted small">No contestants registered.</p>':`<table class="data-table"><thead><tr><th>NO.</th><th>FULL NAME</th><th>SCHOOL / TEAM</th><th>STATUS</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.contestant_no)}</td><td class="table-name"><strong>${esc(r.full_name)}</strong></td><td>${esc(r.school_team||'—')}</td><td><span class="state-chip ${r.attempt_id?r.state:'waiting'}">${r.attempt_id?r.state.toUpperCase():'NOT STARTED'}</span></td></tr>`).join('')}</tbody></table>`}

function preview(text,wrap,master=false){const s=String(text||'').replace(/[^0-9]/g,'').slice(0,81);wrap.innerHTML='';for(let i=0;i<81;i++){const d=document.createElement('span');d.className='mini-cell';if(Math.floor(i/9)%3===2&&Math.floor(i/9)!==8)d.classList.add('box-bottom');const v=s[i]||'';d.textContent=v==='0'&&!master?'':v;wrap.appendChild(d)}}
E.puzzleText.addEventListener('input',()=>preview(E.puzzleText.value,E.puzzlePreview));E.masterText.addEventListener('input',()=>preview(E.masterText.value,E.masterPreview,true));
async function importText(fileInput,target,previewEl,master){const f=fileInput.files?.[0];if(!f)return;target.value=await f.text();preview(target.value,previewEl,master)}
E.puzzleFile.addEventListener('change',()=>importText(E.puzzleFile,E.puzzleText,E.puzzlePreview,false));E.masterFile.addEventListener('change',()=>importText(E.masterFile,E.masterText,E.masterPreview,true));preview('',E.puzzlePreview);preview('',E.masterPreview,true);
E.createForm.addEventListener('submit',async e=>{e.preventDefault();msg(E.createMsg,'Validating puzzle and master key…');try{const d=await api('/api/admin/competitions',{method:'POST',body:{name:E.newName.value,code:E.newCode.value,organization:E.newOrg.value,description:E.newDescription.value,puzzle:E.puzzleText.value,master_key:E.masterText.value,allow_self_registration:E.newSelfReg.checked,show_live_leaderboard:E.newShow.checked}});msg(E.createMsg,'Competition created successfully.','success');toast('Competition created.','success');E.createForm.reset();E.newSelfReg.checked=true;preview('',E.puzzlePreview);preview('',E.masterPreview,true);S.selectedId=d.competition.id;localStorage.setItem('sudoku_live_competition_id',S.selectedId);await loadCompetitions();watchSelected();switchTab('overview')}catch(err){msg(E.createMsg,err.message,'error')}})
E.addForm.addEventListener('submit',async e=>{e.preventDefault();if(!S.selectedId)return msg(E.contestantMsg,'Select a competition first.','error');try{await api(`/api/admin/competitions/${S.selectedId}/contestants`,{method:'POST',body:{contestant_no:E.addNo.value,full_name:E.addName.value,school_team:E.addSchool.value}});E.addForm.reset();msg(E.contestantMsg,'Contestant added.','success');await fetchSnapshot()}catch(err){msg(E.contestantMsg,err.message,'error')}})
E.bulkBtn.addEventListener('click',async()=>{if(!S.selectedId)return msg(E.bulkMsg,'Select a competition first.','error');const rows=E.bulk.value.split(/\r?\n/).map(l=>l.split(',').map(v=>v.trim())).filter(a=>a[0]&&a[1]).map(a=>({contestant_no:a[0],full_name:a[1],school_team:a.slice(2).join(', ')}));if(!rows.length)return msg(E.bulkMsg,'Paste at least one valid CSV row.','error');try{const d=await api(`/api/admin/competitions/${S.selectedId}/contestants/bulk`,{method:'POST',body:{rows}});msg(E.bulkMsg,`${d.inserted} contestant(s) imported.`,'success');E.bulk.value='';await fetchSnapshot()}catch(err){msg(E.bulkMsg,err.message,'error')}})
E.exportBtn.addEventListener('click',async()=>{if(!S.selectedId)return;try{const r=await fetch(`${API_BASE}/api/admin/competitions/${S.selectedId}/results.csv`,{headers:{Authorization:`Bearer ${S.token}`}});if(!r.ok)throw new Error('Export failed');const blob=await r.blob();const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${S.snapshot?.competition?.code||'sudoku'}-results.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(err){toast(err.message,'error')}})

function switchTab(name){$$('.nav-btn[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));$$('.admin-tab').forEach(p=>p.classList.toggle('active',p.dataset.panel===name));E.mobileTab.value=name;window.scrollTo({top:0,behavior:'smooth'})}
$$('.nav-btn[data-tab]').forEach(b=>b.addEventListener('click',()=>switchTab(b.dataset.tab)));E.mobileTab.addEventListener('change',()=>switchTab(E.mobileTab.value));
setInterval(()=>{$$('.live-elapsed').forEach(el=>{const st=Number(el.dataset.start),sub=Number(el.dataset.submitted),em=el.dataset.elapsed===''?null:Number(el.dataset.elapsed);if(st)el.textContent=elapsedFrom(st,sub,em)})},250);
window.addEventListener('online',()=>{setConn('connecting','Connecting');if(S.socket&&!S.socket.connected)S.socket.connect()});window.addEventListener('offline',()=>setConn('offline','Offline'));

(async function init(){if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('./sw.js')}catch{}}if(!S.token){showLogin();setConn(navigator.onLine?'connecting':'offline',navigator.onLine?'Connecting':'Offline');return}showAdmin();try{await loadCompetitions();await connectSocket()}catch(err){toast(err.message,'error')}})();
