'use strict';

const API_BASE='https://suduko.mdmsportal.uk';
const $=s=>document.querySelector(s);
const E={badge:$('#connectionBadge'),lobby:$('#lobbyView'),ready:$('#readyView'),game:$('#gameView'),result:$('#resultView'),joinForm:$('#joinForm'),code:$('#competitionCode'),no:$('#contestantNo'),name:$('#fullName'),school:$('#schoolTeam'),joinMessage:$('#joinMessage'),readyTitle:$('#readyTitle'),readyDescription:$('#readyDescription'),readyName:$('#readyName'),readyNo:$('#readyNo'),readyOrg:$('#readyOrg'),readyDifficulty:$('#readyDifficulty'),readyLimit:$('#readyLimit'),readyParticipation:$('#readyParticipation'),readyMessage:$('#readyMessage'),startBtn:$('#startBtn'),gameTitle:$('#gameTitle'),gamePlayer:$('#gamePlayer'),elapsed:$('#timer'),remaining:$('#remainingTimer'),saveStatus:$('#saveStatus'),board:$('#sudokuBoard'),numberPad:$('#numberPad'),desktopPad:$('#desktopNumberPad'),note:$('#noteBtn'),dNote:$('#desktopNoteBtn'),erase:$('#eraseBtn'),dErase:$('#desktopEraseBtn'),filled:$('#filledCount'),progress:$('#progressBar'),submit:$('#submitBtn'),modal:$('#confirmModal'),cancelSubmit:$('#cancelSubmitBtn'),confirmSubmit:$('#confirmSubmitBtn'),resultIcon:$('#resultIcon'),resultHeadline:$('#resultHeadline'),resultSubline:$('#resultSubline'),resultCorrect:$('#resultCorrect'),resultAccuracy:$('#resultAccuracy'),resultTime:$('#resultTime'),resultRank:$('#resultRank'),leaderboardPanel:$('#leaderboardPanel'),publicLeaderboard:$('#publicLeaderboard'),returnHome:$('#returnHomeBtn'),toasts:$('#toastStack')};
const S={competition:null,contestant:null,attempt:null,token:null,puzzle:'',board:Array(81).fill('0'),notes:Array(81).fill(''),noteMode:false,selected:null,saveTimer:null,saving:false,pendingSave:false,socket:null,serverOffset:0,timerRAF:null,timeUpHandled:false};

function showView(el){[E.lobby,E.ready,E.game,E.result].forEach(v=>v.classList.remove('active'));el.classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function msg(el,text,type=''){el.textContent=text||'';el.className='form-message'+(type?` ${type}`:'')}
function toast(text,type=''){const d=document.createElement('div');d.className='toast '+type;d.textContent=text;E.toasts.appendChild(d);setTimeout(()=>d.remove(),3500)}
function setConn(mode,text){E.badge.className=`status-pill status-${mode}`;E.badge.querySelector('span:last-child').textContent=text}
function fmt(ms){ms=Math.max(0,Number(ms)||0);const m=Math.floor(ms/60000),s=Math.floor((ms%60000)/1000),x=Math.floor(ms%1000);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(x).padStart(3,'0')}`}
function fmtLimit(min){return `${Number(min)||0} minute${Number(min)===1?'':'s'}`}
function norm(v){return String(v??'').replace(/[^0-9]/g,'').slice(0,81)}
function normNotes(v){const a=Array.isArray(v)?v:[];return Array.from({length:81},(_,i)=>[...new Set(String(a[i]||'').replace(/[^1-9]/g,'').split(''))].sort().join(''))}
async function api(path,opts={}){const h={...(opts.headers||{})};if(opts.body&&!(opts.body instanceof FormData)){h['Content-Type']='application/json';if(typeof opts.body!=='string')opts.body=JSON.stringify(opts.body)}const r=await fetch(API_BASE+path,{...opts,headers:h});let d={};try{d=await r.json()}catch{}if(!r.ok){const e=new Error(d.error||`Request failed (${r.status})`);e.data=d;e.status=r.status;throw e}return d}
function mergeClues(answers,puzzle){const a=(norm(answers)+'0'.repeat(81)).slice(0,81).split('');for(let i=0;i<81;i++)if(puzzle[i]&&puzzle[i]!=='0')a[i]=puzzle[i];return a}
function sanitizeLocalNotes(notes){const n=normNotes(notes);for(let i=0;i<81;i++)if(S.puzzle[i]!=='0'||S.board[i]!=='0')n[i]='';return n}
function storeActive(){if(S.token)localStorage.setItem('sudoku_live_active_token',S.token);if(S.attempt)localStorage.setItem('sudoku_live_cached_attempt',JSON.stringify({attempt:S.attempt,board:S.board,notes:S.notes,competition:S.competition,contestant:S.contestant,token:S.token,serverOffset:S.serverOffset}))}
function clearActive(){localStorage.removeItem('sudoku_live_active_token');localStorage.removeItem('sudoku_live_cached_attempt')}
async function health(){try{const r=await fetch(API_BASE+'/health',{cache:'no-store'});if(!r.ok)throw 0;setConn('online','Server Online')}catch{setConn('offline','Server Offline')}}
async function loadSocket(){if(window.io)return true;return new Promise(resolve=>{const s=document.createElement('script');s.src=API_BASE+'/socket.io/socket.io.js';s.async=true;s.onload=()=>resolve(true);s.onerror=()=>resolve(false);document.head.appendChild(s)})}
async function connectSocket(){if(!S.token)return;const ok=await loadSocket();if(!ok){setConn('offline','Live Sync Offline');return}if(S.socket)S.socket.disconnect();S.socket=io(API_BASE,{auth:{attempt_token:S.token},reconnection:true,reconnectionDelay:700,reconnectionDelayMax:3500,transports:['polling','websocket']});S.socket.on('connect',()=>{setConn('online','Live Sync');S.socket.emit('contestant:watch',{competition_id:S.attempt?.competition?.id||S.competition?.id});S.socket.emit('time:sync',{},r=>{if(r?.server_now)S.serverOffset=r.server_now-Date.now()});if(S.pendingSave)queueSave(30)});S.socket.on('disconnect',()=>setConn('connecting','Reconnecting'));S.socket.on('connect_error',()=>setConn('offline','Live Sync Offline'));S.socket.on('server:hello',p=>{if(p?.server_now)S.serverOffset=p.server_now-Date.now()});S.socket.on('competition:status',p=>{if(!p)return;if(S.competition)S.competition.status=p.status;if(S.attempt?.competition)S.attempt.competition.status=p.status;if(p.status==='closed'&&S.attempt?.state==='playing')toast('Competition has been closed. Your latest saved board is being finalized.','error')});S.socket.on('leaderboard:updated',p=>{if(p?.leaderboard){E.leaderboardPanel.classList.remove('hidden');renderLeaderboard(p.leaderboard);const mine=p.leaderboard.find(r=>r.attempt_id===S.attempt?.id);if(mine)E.resultRank.textContent=`#${mine.rank}`}});S.socket.on('attempt:timeup',p=>{if(p?.attempt)finishFromServer(p.attempt,null,true)});S.socket.on('attempt:submitted',p=>{if(p?.attempt&&S.attempt?.state==='playing')finishFromServer(p.attempt,null,false)});S.socket.on('competition:reset',p=>{clearActive();S.token=null;S.attempt=null;S.selected=null;toast(p?.message||'Competition reset by administrator.','error');if(S.socket)S.socket.disconnect();setTimeout(()=>{S.competition=null;S.contestant=null;showView(E.lobby);health()},800)})}

E.joinForm.addEventListener('submit',async e=>{e.preventDefault();msg(E.joinMessage,'Checking competition…');try{const code=E.code.value.trim().toUpperCase(),body={contestant_no:E.no.value.trim(),full_name:E.name.value.trim(),school_team:E.school.value.trim()},d=await api(`/api/competitions/${encodeURIComponent(code)}/check-in`,{method:'POST',body});S.competition=d.competition;S.contestant=d.contestant;localStorage.setItem('sudoku_live_last_identity',JSON.stringify({code,...body}));E.readyTitle.textContent=S.competition.name;E.readyDescription.textContent=S.competition.description||'Solve accurately and submit as fast as you can.';E.readyName.textContent=S.contestant.full_name;E.readyNo.textContent=S.contestant.contestant_no;E.readyOrg.textContent=S.competition.organization||'Competition Organizer';E.readyDifficulty.textContent=S.competition.difficulty;E.readyLimit.textContent=fmtLimit(S.competition.time_limit_minutes);E.readyParticipation.textContent=S.competition.participation_mode==='limited'?`${S.competition.slots_remaining} slot(s) remaining`:'Open Play';E.startBtn.textContent=d.has_active_attempt?'RESUME SUDOKU →':'START SUDOKU →';msg(E.joinMessage,'');showView(E.ready)}catch(err){msg(E.joinMessage,err.message,'error')}});
E.startBtn.addEventListener('click',async()=>{if(!S.competition||!S.contestant)return;E.startBtn.disabled=true;msg(E.readyMessage,'Securing your official attempt…');try{const remembered=localStorage.getItem('sudoku_live_active_token')||'',d=await api(`/api/competitions/${encodeURIComponent(S.competition.code)}/start`,{method:'POST',body:{contestant_no:S.contestant.contestant_no,full_name:S.contestant.full_name,attempt_token:remembered}});S.token=d.attempt_token;S.attempt=d.attempt;S.serverOffset=(d.server_now||Date.now())-Date.now();S.puzzle=d.attempt.competition.puzzle;S.board=mergeClues(d.attempt.answers,S.puzzle);S.notes=normNotes(d.attempt.notes);S.notes=sanitizeLocalNotes(S.notes);S.noteMode=false;S.competition={...S.competition,...d.attempt.competition};S.timeUpHandled=false;storeActive();enterGame();await connectSocket();toast(d.resumed?'Attempt resumed. Official timer continued.':'Official timer started.','success')}catch(err){msg(E.readyMessage,err.message,'error')}finally{E.startBtn.disabled=false}});

function enterGame(){showView(E.game);E.gameTitle.textContent=S.attempt?.competition?.name||S.competition?.name||'Sudoku Competition';const c=S.contestant||S.attempt?.contestant;E.gamePlayer.textContent=`${c?.contestant_no||''} · ${c?.full_name||''}`;renderBoard();renderPads();updateNoteButtons();startTimer();updateProgress();setTimeout(()=>selectFirstEditable(),50)}
function renderPads(){for(const wrap of [E.numberPad,E.desktopPad]){wrap.innerHTML='';for(let n=1;n<=9;n++){const b=document.createElement('button');b.className='number-key';b.textContent=n;b.type='button';b.addEventListener('click',()=>inputDigit(String(n)));wrap.appendChild(b)}}}
function renderCell(i){const cell=E.board.children[i];if(!cell)return;cell.innerHTML='';const value=document.createElement('span');value.className='cell-value';value.textContent=S.board[i]==='0'?'':S.board[i];cell.appendChild(value);const note=document.createElement('span');note.className='cell-note';note.textContent=(S.board[i]==='0'&&S.puzzle[i]==='0')?(S.notes[i]||''):'';cell.appendChild(note);cell.classList.toggle('player-value',S.puzzle[i]==='0'&&S.board[i]!=='0');cell.setAttribute('aria-label',`Row ${Math.floor(i/9)+1}, column ${i%9+1}${note.textContent?`, notes ${note.textContent.split('').join(' ')}`:''}`)}
function renderBoard(){E.board.innerHTML='';for(let i=0;i<81;i++){const b=document.createElement('button');b.type='button';b.className='sudoku-cell';b.dataset.index=i;b.setAttribute('role','gridcell');b.tabIndex=i===0?0:-1;if(Math.floor(i/9)%3===2&&Math.floor(i/9)!==8)b.classList.add('box-bottom');if(S.puzzle[i]!=='0')b.classList.add('clue');b.addEventListener('click',()=>selectCell(i,true));E.board.appendChild(b);renderCell(i)}updateSelection()}
function selectCell(i,focus=false){if(i<0||i>80)return;S.selected=i;updateSelection();if(focus){const cell=E.board.children[i];cell?.focus({preventScroll:true})}}
function selectFirstEditable(){if(S.selected!=null)return;const i=S.puzzle.indexOf('0');if(i>=0)selectCell(i,false)}
function updateSelection(){[...E.board.children].forEach((el,i)=>{el.classList.toggle('selected',i===S.selected);el.tabIndex=i===S.selected?0:-1})}
function moveSelection(dr,dc){let i=S.selected==null?0:S.selected,r=Math.floor(i/9),c=i%9;r=Math.max(0,Math.min(8,r+dr));c=Math.max(0,Math.min(8,c+dc));selectCell(r*9+c,true)}
function setFinalValue(v){if(S.attempt?.state!=='playing'||S.selected==null||S.puzzle[S.selected]!=='0')return;S.board[S.selected]=v;S.notes[S.selected]='';renderCell(S.selected);updateProgress();storeActive();queueSave()}
function toggleCellNote(v){if(S.attempt?.state!=='playing'||S.selected==null||S.puzzle[S.selected]!=='0'||S.board[S.selected]!=='0')return;const set=new Set((S.notes[S.selected]||'').split('').filter(Boolean));set.has(v)?set.delete(v):set.add(v);S.notes[S.selected]=[...set].sort().join('');renderCell(S.selected);storeActive();queueSave()}
function inputDigit(v){S.noteMode?toggleCellNote(v):setFinalValue(v)}
function eraseSelected(){if(S.attempt?.state!=='playing'||S.selected==null||S.puzzle[S.selected]!=='0')return;if(S.noteMode){S.notes[S.selected]='';renderCell(S.selected);storeActive();queueSave()}else setFinalValue('0')}
function toggleNoteMode(force){if(S.attempt?.state!=='playing')return;S.noteMode=typeof force==='boolean'?force:!S.noteMode;updateNoteButtons()}
function updateNoteButtons(){for(const b of [E.note,E.dNote]){if(!b)continue;b.classList.toggle('active',S.noteMode);const sm=b.querySelector('small');if(sm)sm.textContent=S.noteMode?'Note ON':'Note';b.setAttribute('aria-pressed',S.noteMode?'true':'false')}}
function updateProgress(){const entered=S.board.reduce((n,v,i)=>n+(S.puzzle[i]==='0'&&v!=='0'?1:0),0),blanks=[...S.puzzle].filter(x=>x==='0').length,filled=81-blanks+entered;E.filled.textContent=filled;E.progress.style.width=`${Math.min(100,(filled/81)*100)}%`;const editable=S.attempt?.state==='playing'&&S.competition?.status!=='closed';E.submit.disabled=!editable}
function queueSave(delay=350){if(S.attempt?.state!=='playing')return;clearTimeout(S.saveTimer);S.pendingSave=true;E.saveStatus.textContent=navigator.onLine?'Saving…':'Offline — latest server save will be used at time limit';S.saveTimer=setTimeout(saveNow,delay)}
async function saveNow(){if(S.saving||!S.pendingSave||!S.token||S.attempt?.state!=='playing')return;S.saving=true;S.pendingSave=false;try{const d=await api('/api/attempt/answers',{method:'PUT',headers:{'X-Attempt-Token':S.token},body:{answers:S.board.join(''),notes:S.notes}});E.saveStatus.textContent='All changes saved';if(d.server_now)S.serverOffset=d.server_now-Date.now();if(S.attempt)S.attempt.last_saved_at=d.last_saved_at;storeActive()}catch(err){if(err.data?.submitted){await refreshAttemptAfterDeadline();return}S.pendingSave=true;E.saveStatus.textContent=navigator.onLine?'Save retry pending':'Offline — reconnect to sync'}finally{S.saving=false}}
function startTimer(){cancelAnimationFrame(S.timerRAF);const tick=()=>{if(!S.attempt)return;const now=Date.now()+S.serverOffset,elapsed=S.attempt.state==='submitted'?Number(S.attempt.elapsed_ms||0):Math.max(0,now-Number(S.attempt.started_at||now)),remaining=S.attempt.state==='submitted'?0:Math.max(0,Number(S.attempt.deadline_at||now)-now);E.elapsed.textContent=fmt(elapsed);E.remaining.textContent=fmt(remaining);E.remaining.closest('.timer-block')?.classList.toggle('timer-warning',remaining>0&&remaining<=60000);if(S.attempt.state==='playing'&&remaining<=0&&!S.timeUpHandled){S.timeUpHandled=true;E.saveStatus.textContent='Time is up — finalizing latest saved board…';lockBoard();refreshAttemptAfterDeadline()}S.timerRAF=requestAnimationFrame(tick)};tick()}
function lockBoard(){E.submit.disabled=true;E.erase.disabled=true;E.dErase.disabled=true;E.note.disabled=true;E.dNote.disabled=true;for(const b of E.numberPad.querySelectorAll('button'))b.disabled=true;for(const b of E.desktopPad.querySelectorAll('button'))b.disabled=true}
function unlockBoard(){E.erase.disabled=false;E.dErase.disabled=false;E.note.disabled=false;E.dNote.disabled=false;for(const b of E.numberPad.querySelectorAll('button'))b.disabled=false;for(const b of E.desktopPad.querySelectorAll('button'))b.disabled=false;updateProgress()}
async function refreshAttemptAfterDeadline(){try{const d=await api('/api/attempt',{headers:{'X-Attempt-Token':S.token}});if(d.server_now)S.serverOffset=d.server_now-Date.now();if(d.attempt?.state==='submitted')finishFromServer(d.attempt,null,d.attempt.submission_type==='time_limit');else{S.timeUpHandled=false;unlockBoard()}}catch{setTimeout(()=>refreshAttemptAfterDeadline(),1500)}}

E.note.addEventListener('click',()=>toggleNoteMode());E.dNote.addEventListener('click',()=>toggleNoteMode());E.erase.addEventListener('click',eraseSelected);E.dErase.addEventListener('click',eraseSelected);
document.addEventListener('keydown',e=>{if(!E.game.classList.contains('active')||S.attempt?.state!=='playing')return;const key=e.key;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(key)){e.preventDefault();if(key==='ArrowLeft')moveSelection(0,-1);if(key==='ArrowRight')moveSelection(0,1);if(key==='ArrowUp')moveSelection(-1,0);if(key==='ArrowDown')moveSelection(1,0);return}if(key==='n'||key==='N'){e.preventDefault();toggleNoteMode();return}if(/^[1-9]$/.test(key)){e.preventDefault();inputDigit(key);return}if(key==='Backspace'||key==='Delete'||key==='0'){e.preventDefault();eraseSelected()}});
E.submit.addEventListener('click',()=>{if(S.attempt?.state!=='playing')return;E.modal.classList.add('open');E.modal.setAttribute('aria-hidden','false')});
E.cancelSubmit.addEventListener('click',()=>closeModal());E.modal.querySelector('.modal-backdrop')?.addEventListener('click',closeModal);function closeModal(){E.modal.classList.remove('open');E.modal.setAttribute('aria-hidden','true')}
E.confirmSubmit.addEventListener('click',async()=>{closeModal();E.submit.disabled=true;E.confirmSubmit.disabled=true;E.saveStatus.textContent='Submitting final answer…';try{if(S.pendingSave)await saveNow();const d=await api('/api/attempt/submit',{method:'POST',headers:{'X-Attempt-Token':S.token},body:{answers:S.board.join(''),notes:S.notes}});finishFromServer(d.result,d.rank,false);if(d.leaderboard_visible)loadLeaderboard()}catch(err){if(err.data?.result){finishFromServer(err.data.result,null,err.data.result.submission_type==='time_limit')}else{toast(err.message,'error');E.submit.disabled=false}}finally{E.confirmSubmit.disabled=false}});
function finishFromServer(attempt,rank=null,timeUp=false){S.attempt=attempt;S.board=mergeClues(attempt.answers,attempt.competition.puzzle);S.puzzle=attempt.competition.puzzle;S.notes=normNotes(attempt.notes);S.noteMode=false;updateNoteButtons();S.timeUpHandled=true;storeActive();lockBoard();cancelAnimationFrame(S.timerRAF);E.resultCorrect.textContent=`${attempt.correct_count}/81`;E.resultAccuracy.textContent=`${Number(attempt.accuracy||0).toFixed(2)}%`;E.resultTime.textContent=fmt(attempt.elapsed_ms);E.resultRank.textContent=rank?`#${rank}`:'Pending';E.resultIcon.textContent=attempt.is_perfect?'✓':timeUp?'⏱':'•';E.resultHeadline.textContent=timeUp?'Time is up — sheet auto-submitted':attempt.is_perfect?'Perfect submission':'Submission recorded';E.resultSubline.textContent=timeUp?'Your latest server-saved answers were automatically submitted at the official time limit.':'Your result has been secured by the competition server.';showView(E.result);if(S.competition?.show_live_leaderboard||S.competition?.status==='closed')loadLeaderboard()}
async function loadLeaderboard(){try{const d=await api(`/api/competitions/${encodeURIComponent(S.competition.code)}/leaderboard`);E.leaderboardPanel.classList.remove('hidden');renderLeaderboard(d.leaderboard);const mine=d.leaderboard.find(r=>r.attempt_id===S.attempt?.id);if(mine)E.resultRank.textContent=`#${mine.rank}`}catch{}}
function renderLeaderboard(rows){E.publicLeaderboard.innerHTML=rows.slice(0,20).map(r=>`<div class="leaderboard-row ${r.rank<=3?'top':''}"><span>#${r.rank}</span><strong>${escapeHtml(r.full_name)}</strong><small>${r.correct_count}/81 · ${fmt(r.elapsed_ms)}</small></div>`).join('')||'<p class="muted small">No results yet.</p>'}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
E.returnHome.addEventListener('click',()=>{clearActive();if(S.socket)S.socket.disconnect();S.competition=null;S.contestant=null;S.attempt=null;S.token=null;S.selected=null;S.notes=Array(81).fill('');S.noteMode=false;showView(E.lobby);health()});
async function restoreAttempt(){const token=localStorage.getItem('sudoku_live_active_token');if(!token)return false;try{const d=await api('/api/attempt',{headers:{'X-Attempt-Token':token}});S.token=token;S.attempt=d.attempt;S.serverOffset=(d.server_now||Date.now())-Date.now();S.competition=d.attempt.competition;S.contestant=d.attempt.contestant;S.puzzle=d.attempt.competition.puzzle;S.board=mergeClues(d.attempt.answers,S.puzzle);S.notes=normNotes(d.attempt.notes);S.notes=sanitizeLocalNotes(S.notes);if(d.attempt.state==='submitted'){finishFromServer(d.attempt,null,d.attempt.submission_type==='time_limit');await connectSocket();return true}storeActive();enterGame();await connectSocket();return true}catch{try{const cached=JSON.parse(localStorage.getItem('sudoku_live_cached_attempt')||'null');if(cached?.attempt?.state==='playing'&&!navigator.onLine){S.token=cached.token;S.attempt=cached.attempt;S.competition=cached.competition;S.contestant=cached.contestant;S.serverOffset=Number(cached.serverOffset||0);S.puzzle=cached.attempt.competition.puzzle;S.board=mergeClues(cached.board?.join?.('')||cached.attempt.answers,S.puzzle);S.notes=normNotes(cached.notes||cached.attempt.notes);S.notes=sanitizeLocalNotes(S.notes);enterGame();setConn('offline','Offline');E.saveStatus.textContent='Offline — latest server save will be used at time limit';return true}}catch{}return false}}
window.addEventListener('online',()=>{setConn('connecting','Connecting');if(S.socket&&!S.socket.connected)S.socket.connect();if(S.pendingSave)queueSave(20)});window.addEventListener('offline',()=>setConn('offline','Offline'));
(async function init(){if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('./sw.js')}catch{}}const last=JSON.parse(localStorage.getItem('sudoku_live_last_identity')||'null');if(last){E.code.value=last.code||'';E.no.value=last.contestant_no||'';E.name.value=last.full_name||'';E.school.value=last.school_team||''}await health();await restoreAttempt()})();
